package metricsstore

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strconv"
	"sync"
	"sync/atomic"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// PostgresStore persists metrics and request logs in PostgreSQL. Writes are
// serialized to keep the read/modify/write aggregate update atomic while the
// database connection pool handles concurrent readers and instances.
type PostgresStore struct {
	db            *sql.DB
	mu            sync.RWMutex
	requestWrites int
	retention     atomic.Pointer[Retention]
}

// OpenPostgres opens and initializes a PostgreSQL metrics store. The DSN may
// be any pgx-supported URL, for example
// postgres://user:password@host:5432/dbname?sslmode=disable.
func OpenPostgres(dsn string, maxOpenConns, maxIdleConns int, connMaxLifetime, connMaxIdleTime time.Duration) (*PostgresStore, error) {
	if dsn == "" {
		return nil, fmt.Errorf("postgres DSN is empty")
	}
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, fmt.Errorf("open postgres: %w", err)
	}
	if maxOpenConns <= 0 {
		maxOpenConns = 16
	}
	if maxIdleConns <= 0 || maxIdleConns > maxOpenConns {
		maxIdleConns = maxOpenConns / 2
		if maxIdleConns < 1 {
			maxIdleConns = 1
		}
	}
	db.SetMaxOpenConns(maxOpenConns)
	db.SetMaxIdleConns(maxIdleConns)
	if connMaxLifetime > 0 {
		db.SetConnMaxLifetime(connMaxLifetime)
	}
	if connMaxIdleTime > 0 {
		db.SetConnMaxIdleTime(connMaxIdleTime)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	if err := initPostgresSchema(ctx, db); err != nil {
		db.Close()
		return nil, err
	}
	s := &PostgresStore{db: db}
	s.SetRetention(Retention{}) // orDefault → 旧默认 1 万条
	return s, nil
}

// SetRetention 更新保留策略（运行时可调）。与 SQLite 版语义一致。
func (s *PostgresStore) SetRetention(r Retention) {
	s.retention.Store(&r)
}

// RetentionPolicy 返回当前策略（回显用）。
func (s *PostgresStore) RetentionPolicy() Retention {
	if p := s.retention.Load(); p != nil {
		return *p
	}
	return Retention{}
}

func initPostgresSchema(ctx context.Context, db *sql.DB) error {
	if _, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS metrics (
		id BIGINT PRIMARY KEY CHECK (id = 1),
		data JSONB NOT NULL,
		updated_at BIGINT NOT NULL
	)`); err != nil {
		return fmt.Errorf("create postgres metrics table: %w", err)
	}
	// Seed the singleton row once so concurrent application instances always
	// contend on the same row lock instead of racing on a missing row.
	if _, err := db.ExecContext(ctx, `INSERT INTO metrics(id, data, updated_at)
		VALUES(1, '{}'::jsonb, 0) ON CONFLICT(id) DO NOTHING`); err != nil {
		return fmt.Errorf("initialize postgres metrics row: %w", err)
	}
	if _, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS request_logs (
		log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		id TEXT NOT NULL DEFAULT '',
		created_at BIGINT NOT NULL,
		route TEXT NOT NULL,
		model TEXT NOT NULL,
		mode TEXT NOT NULL,
		status INTEGER NOT NULL,
		account_uid TEXT NOT NULL DEFAULT '',
		account_region TEXT NOT NULL DEFAULT '',
		requested_output_tokens BIGINT NOT NULL DEFAULT 0,
		input_tokens BIGINT NOT NULL DEFAULT 0,
		output_tokens BIGINT NOT NULL DEFAULT 0,
		total_tokens BIGINT NOT NULL DEFAULT 0,
		cache_read_tokens BIGINT NOT NULL DEFAULT 0,
		cache_write_tokens BIGINT NOT NULL DEFAULT 0,
		tool_calls BIGINT NOT NULL DEFAULT 0,
		ttfb_millis BIGINT NOT NULL DEFAULT 0,
		latency_millis BIGINT NOT NULL DEFAULT 0,
		credits_consumed DOUBLE PRECISION NOT NULL DEFAULT 0,
		credit_source TEXT NOT NULL DEFAULT '',
		passthrough BOOLEAN NOT NULL DEFAULT FALSE,
		error_code TEXT NOT NULL DEFAULT '',
		error_message TEXT NOT NULL DEFAULT ''
	)`); err != nil {
		return fmt.Errorf("create postgres request_logs table: %w", err)
	}
	if _, err := db.ExecContext(ctx, `ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS error_message TEXT NOT NULL DEFAULT ''`); err != nil {
		return fmt.Errorf("migrate postgres request_logs: %w", err)
	}
	if _, err := db.ExecContext(ctx, `ALTER TABLE request_logs ADD COLUMN IF NOT EXISTS account_region TEXT NOT NULL DEFAULT ''`); err != nil {
		return fmt.Errorf("migrate postgres request_logs region: %w", err)
	}
	if _, err := db.ExecContext(ctx, `CREATE INDEX IF NOT EXISTS request_logs_created_at_idx ON request_logs(created_at DESC, log_id DESC)`); err != nil {
		return fmt.Errorf("create postgres request_logs index: %w", err)
	}
	return nil
}

type postgresExecutor interface {
	QueryRow(query string, args ...any) *sql.Row
	Exec(query string, args ...any) (sql.Result, error)
}

func (s *PostgresStore) Add(delta Snapshot) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err := addDeltaPostgres(tx, delta); err != nil {
		return err
	}
	return tx.Commit()
}

func addDeltaPostgres(db postgresExecutor, delta Snapshot) error {
	current, err := readSnapshotPostgres(db)
	if err != nil {
		return err
	}
	current.Requests += delta.Requests
	current.Successes += delta.Successes
	current.Failures += delta.Failures
	current.InputTokens += delta.InputTokens
	current.OutputTokens += delta.OutputTokens
	current.TotalTokens += delta.TotalTokens
	current.CacheRead += delta.CacheRead
	current.CacheWrite += delta.CacheWrite
	current.ToolCalls += delta.ToolCalls
	current.TTFBMillis += delta.TTFBMillis
	current.TTFBSamples += delta.TTFBSamples
	current.LatencyMillis += delta.LatencyMillis
	current.CreditsConsumed += delta.CreditsConsumed
	current.CreditsUpstream += delta.CreditsUpstream
	current.CreditsEstimated += delta.CreditsEstimated
	current.CreditRequests += delta.CreditRequests
	if delta.LastRequestUnix > current.LastRequestUnix {
		current.LastRequestUnix = delta.LastRequestUnix
	}
	raw, err := json.Marshal(current)
	if err != nil {
		return err
	}
	_, err = db.Exec(`INSERT INTO metrics(id, data, updated_at) VALUES($1, $2::jsonb, $3)
		ON CONFLICT(id) DO UPDATE SET data=EXCLUDED.data, updated_at=EXCLUDED.updated_at`, 1, string(raw), time.Now().Unix())
	return err
}

func readSnapshotPostgres(db postgresExecutor) (Snapshot, error) {
	var raw []byte
	query := `SELECT data FROM metrics WHERE id=$1`
	// Aggregate updates run inside a transaction; lock the single metrics row
	// so multiple application instances cannot lose increments.
	if _, ok := db.(*sql.Tx); ok {
		query += ` FOR UPDATE`
	}
	err := db.QueryRow(query, 1).Scan(&raw)
	if err == sql.ErrNoRows {
		return Snapshot{}, nil
	}
	if err != nil {
		return Snapshot{}, err
	}
	var snapshot Snapshot
	if err := json.Unmarshal(raw, &snapshot); err != nil {
		return Snapshot{}, fmt.Errorf("decode postgres metrics: %w", err)
	}
	return snapshot, nil
}

func (s *PostgresStore) AddCredit(consumed float64, source string) error {
	if consumed <= 0 {
		return nil
	}
	delta := Snapshot{CreditsConsumed: consumed, CreditRequests: 1}
	switch source {
	case "upstream":
		delta.CreditsUpstream = consumed
	case "estimated":
		delta.CreditsEstimated = consumed
	}
	return s.Add(delta)
}

func (s *PostgresStore) RecordRequest(record RequestRecord) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	err := insertRequestPostgres(s.db, record, s.requestWrites+1, s.RetentionPolicy())
	if err == nil {
		s.requestWrites++
	}
	return err
}

func (s *PostgresStore) RecordCompletion(delta Snapshot, record RequestRecord) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if err = addDeltaPostgres(tx, delta); err != nil {
		return err
	}
	if err = insertRequestPostgres(tx, record, s.requestWrites+1, s.RetentionPolicy()); err != nil {
		return err
	}
	if err = tx.Commit(); err == nil {
		s.requestWrites++
	}
	return err
}

func (s *PostgresStore) ReconcileRequestCredit(id string, credit float64) error {
	if id == "" || credit < 0 {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var old float64
	var source string
	var logID int64
	err = tx.QueryRow(`SELECT log_id, credits_consumed, credit_source FROM request_logs WHERE id=$1 ORDER BY log_id DESC LIMIT 1 FOR UPDATE`, id).Scan(&logID, &old, &source)
	if err == sql.ErrNoRows {
		return nil
	}
	if err != nil {
		return err
	}
	if source == "upstream" && old == credit {
		return nil
	}
	delta := Snapshot{CreditsConsumed: credit - old, CreditsUpstream: credit - old}
	switch source {
	case "estimated":
		delta.CreditsEstimated = -old
		delta.CreditsUpstream = credit
	case "unknown":
		delta.CreditRequests = 1
		delta.CreditsUpstream = credit
	}
	if err = addDeltaPostgres(tx, delta); err != nil {
		return err
	}
	if _, err = tx.Exec(`UPDATE request_logs SET credits_consumed=$1, credit_source='upstream' WHERE log_id=$2`, credit, logID); err != nil {
		return err
	}
	return tx.Commit()
}

func insertRequestPostgres(db postgresExecutor, record RequestRecord, writes int, retention Retention) error {
	_, err := db.Exec(`INSERT INTO request_logs(
		id, created_at, route, model, mode, status, account_uid, account_region, requested_output_tokens,
		input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens,
		tool_calls, ttfb_millis, latency_millis, credits_consumed, credit_source,
		passthrough, error_code, error_message
	) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)`,
		record.ID, record.CreatedAt, record.Route, record.Model, record.Mode, record.Status, record.AccountUID, record.AccountRegion, record.RequestedOutputTokens,
		record.InputTokens, record.OutputTokens, record.TotalTokens, record.CacheReadTokens, record.CacheWriteTokens,
		record.ToolCalls, record.TTFBMillis, record.LatencyMillis, record.CreditsConsumed, record.CreditSource,
		record.Passthrough, record.ErrorCode, record.ErrorMessage)
	if err == nil && writes%100 == 0 {
		err = trimRequestLogsPostgres(db, retention)
	}
	return err
}

// trimRequestLogsPostgres 与 SQLite 版 trimRequestLogs 同语义：时间与条数
// 双条件同时生效，任一命中即删。
func trimRequestLogsPostgres(db postgresExecutor, retention Retention) error {
	cutoff := retention.cutoffUnix(time.Now())
	rowsCap := retention.rowsCap()
	if cutoff == 0 && rowsCap == 0 {
		return nil
	}
	var err error
	if cutoff > 0 {
		if _, err = db.Exec(`DELETE FROM request_logs WHERE created_at < $1`, cutoff); err != nil {
			return err
		}
	}
	if rowsCap > 0 {
		_, err = db.Exec(`DELETE FROM request_logs WHERE log_id IN (
			SELECT log_id FROM request_logs ORDER BY created_at DESC, log_id DESC OFFSET $1
		)`, rowsCap)
	}
	return err
}

func (s *PostgresStore) RecentRequests(limit int) ([]RequestRecord, error) {
	return s.QueryRequests(RequestFilter{Limit: limit})
}

// QueryRequests returns request log rows matching the filter, newest first.
func (s *PostgresStore) QueryRequests(filter RequestFilter) ([]RequestRecord, error) {
	limit := filter.Limit
	if limit <= 0 || limit > 500 {
		limit = 50
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	where, args := requestFilterWhere(filter, "$")
	rows, err := s.db.Query(`SELECT id, created_at, route, model, mode, status, account_uid, account_region, requested_output_tokens,
		input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens,
		tool_calls, ttfb_millis, latency_millis, credits_consumed, credit_source, passthrough, error_code, error_message
		FROM request_logs`+where+` ORDER BY created_at DESC, log_id DESC LIMIT $`+strconv.Itoa(len(args)+1), append(args, limit)...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []RequestRecord
	for rows.Next() {
		var record RequestRecord
		if err := rows.Scan(&record.ID, &record.CreatedAt, &record.Route, &record.Model, &record.Mode, &record.Status, &record.AccountUID, &record.AccountRegion, &record.RequestedOutputTokens,
			&record.InputTokens, &record.OutputTokens, &record.TotalTokens, &record.CacheReadTokens, &record.CacheWriteTokens,
			&record.ToolCalls, &record.TTFBMillis, &record.LatencyMillis, &record.CreditsConsumed, &record.CreditSource, &record.Passthrough, &record.ErrorCode, &record.ErrorMessage); err != nil {
			return nil, err
		}
		out = append(out, record)
	}
	return out, rows.Err()
}

// SummarizeRequests aggregates every matching row without a LIMIT cap.
func (s *PostgresStore) SummarizeRequests(filter RequestFilter) (RequestSummary, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	where, args := requestFilterWhere(filter, "$")
	row := s.db.QueryRow(`SELECT COUNT(*),
		COALESCE(SUM(CASE WHEN status >= 200 AND status < 300 THEN 1 ELSE 0 END), 0),
		COALESCE(SUM(CASE WHEN status >= 200 AND status < 300 THEN 0 ELSE 1 END), 0),
		COALESCE(SUM(input_tokens), 0), COALESCE(SUM(output_tokens), 0), COALESCE(SUM(total_tokens), 0),
		COALESCE(SUM(cache_read_tokens), 0), COALESCE(SUM(cache_write_tokens), 0), COALESCE(SUM(tool_calls), 0),
		COALESCE(SUM(ttfb_millis), 0), COALESCE(SUM(CASE WHEN ttfb_millis > 0 THEN 1 ELSE 0 END), 0),
		COALESCE(SUM(latency_millis), 0), COALESCE(SUM(credits_consumed), 0)
		FROM request_logs`+where, args...)
	var summary RequestSummary
	if err := row.Scan(&summary.Requests, &summary.Successes, &summary.Failures,
		&summary.InputTokens, &summary.OutputTokens, &summary.TotalTokens,
		&summary.CacheReadTokens, &summary.CacheWriteTokens, &summary.ToolCalls,
		&summary.TTFBMillisSum, &summary.TTFBSamples, &summary.LatencyMillisSum,
		&summary.CreditsConsumed); err != nil {
		return RequestSummary{}, err
	}
	return summary, nil
}

func (s *PostgresStore) Snapshot() (Snapshot, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return readSnapshotPostgres(s.db)
}

func (s *PostgresStore) Close() error { return s.db.Close() }

var _ Backend = (*PostgresStore)(nil)
